# Generated by Django 4.2.7 on 2023-11-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                ("name_sa", models.CharField(editable=False, max_length=50)),
                (
                    "id_card",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="id card"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                ("birth", models.DateField(verbose_name="birth")),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="state"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("BR", "Brazil"), ("US", "United States")],
                        default="BR",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("PW", "Public Work"),
                            ("YW", "Youth Work"),
                            ("PG", "Guest of Pupil"),
                            ("A1", "1st. Aspect"),
                            ("A2", "2st. Aspect"),
                            ("A3", "3st. Aspect"),
                            ("A4", "4st. Aspect"),
                            ("GR", "Grail"),
                            ("A5", "5st. Aspect"),
                            ("A6", "6st. Aspect"),
                        ],
                        default="PW",
                        max_length=20,
                        verbose_name="aspect",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "sos_contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="sos contact"
                    ),
                ),
                (
                    "sos_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="sos phone"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="center.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ["name_sa"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PersonStay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lodge",
                    models.CharField(
                        choices=[("LDG", "Lodge"), ("HSE", "House"), ("HTL", "Hotel")],
                        default="LDG",
                        max_length=3,
                        verbose_name="lodge",
                    ),
                ),
                (
                    "arrival_time",
                    models.CharField(
                        choices=[
                            ("0BD", "Eve day, before dinner."),
                            ("0AD", "Eve day, after dinner."),
                            ("1BB", "First day, before breakfast."),
                            ("1BL", "First day, before lunch."),
                            ("1BD", "First day, before dinner."),
                            ("1AD", "First day, after dinner."),
                            ("2BB", "Second day, before breakfast."),
                        ],
                        default="1BL",
                        max_length=3,
                        verbose_name="arrival time",
                    ),
                ),
                (
                    "departure_time",
                    models.CharField(
                        choices=[
                            ("1BL", "First day, before lunch."),
                            ("1BD", "First day, before dinner."),
                            ("1AD", "First day, after dinner."),
                            ("2BB", "Second day, before breakfast."),
                            ("2BL", "Second day, before lunch."),
                            ("2AL", "Second day, after lunch."),
                        ],
                        default="2AL",
                        max_length=3,
                        verbose_name="departure time",
                    ),
                ),
                (
                    "no_stairs",
                    models.BooleanField(default=False, verbose_name="no stairs"),
                ),
                ("no_bunk", models.BooleanField(default=False, verbose_name="no bunk")),
                ("bedroom", models.IntegerField(default=0, verbose_name="bedroom")),
                (
                    "bedroom_alt",
                    models.IntegerField(default=0, verbose_name="bedroom alt"),
                ),
                (
                    "bedroom_type",
                    models.CharField(
                        choices=[("B", "Bottom"), ("T", "Top")],
                        default="B",
                        max_length=1,
                        verbose_name="bedroom type",
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="person.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True, to="person.staff", verbose_name="staff"
                    ),
                ),
                (
                    "stay_center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="center.center",
                        verbose_name="stay center",
                    ),
                ),
            ],
            options={
                "verbose_name": "person stay",
                "verbose_name_plural": "person stays",
                "ordering": ["person__name_sa"],
            },
        ),
    ]
