# Generated by Django 4.2 on 2023-04-26 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0002_alter_center_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                ("name_sa", models.CharField(editable=False, max_length=50)),
                ("short_name", models.CharField(editable=False, max_length=30)),
                (
                    "id_card",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="id card"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                ("birth", models.DateField(verbose_name="birth")),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="state"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("BR", "Brazil"), ("US", "United States")],
                        default="BR",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("PW", "Public Work"),
                            ("YW", "Youth Work"),
                            ("PG", "Guest of Pupil"),
                            ("A1", "1st. Aspect"),
                            ("A2", "2st. Aspect"),
                            ("A3", "3st. Aspect"),
                            ("A4", "4st. Aspect"),
                            ("GR", "Grail"),
                            ("A5", "5st. Aspect"),
                            ("A6", "6st. Aspect"),
                        ],
                        default="PW",
                        max_length=20,
                        verbose_name="aspect",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "sos_contact",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="sos contact"
                    ),
                ),
                (
                    "sos_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="sos phone"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=7,
                        verbose_name="credit",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="observations"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="center.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ["name_sa"],
            },
        ),
    ]
