# Generated by Django 4.2 on 2023-04-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="observations",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="observations"
            ),
        ),
        migrations.CreateModel(
            name="CreditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=7,
                        verbose_name="credit",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("ADJ", "Adjustment"),
                            ("GEN", "Generation"),
                            ("USE", "Useded"),
                            ("CAN", "Cancel"),
                            ("EXC", "Exclusion"),
                            ("DEV", "Devolution"),
                            ("CML", "Cancel Multiple"),
                            ("RPY", "Repayment"),
                        ],
                        default="ADJ",
                        max_length=3,
                        verbose_name="operation",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_credit_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_credit_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_logs",
                        to="person.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit log",
                "verbose_name_plural": "credit logs",
                "ordering": ["-created_on"],
            },
        ),
    ]
