# Generated by Django 4.2 on 2023-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_alter_person_observations_creditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("ADJ", "Adjustment"),
                    ("GEN", "Generation"),
                    ("USE", "Used"),
                    ("CAN", "Cancel"),
                    ("EXC", "Exclusion"),
                    ("DEV", "Devolution"),
                    ("CML", "Cancel Multiple"),
                    ("RPY", "Repayment"),
                ],
                default="ADJ",
                max_length=3,
                verbose_name="operation",
            ),
        ),
    ]
