# Generated by Django 4.2.8 on 2024-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_alter_person_id_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="personstay",
            name="meals",
            field=models.JSONField(
                blank=True, editable=False, null=True, verbose_name="meals"
            ),
        ),
        migrations.AddField(
            model_name="personstay",
            name="take_meals",
            field=models.BooleanField(default=True, verbose_name="take meals?"),
        ),
        migrations.AlterField(
            model_name="personstay",
            name="arrival_time",
            field=models.CharField(
                choices=[
                    ("A0BD", "Eve day, before dinner."),
                    ("A0AD", "Eve day, after dinner."),
                    ("A1BB", "1st. day, before breakfast."),
                    ("A1BL", "1st. day, before lunch."),
                    ("A1BD", "1st. day, before dinner."),
                    ("A1AD", "1st. day, after dinner."),
                    ("A2BB", "2nd. day, before breakfast."),
                ],
                default="A1BL",
                max_length=4,
                verbose_name="arrival time",
            ),
        ),
        migrations.AlterField(
            model_name="personstay",
            name="departure_time",
            field=models.CharField(
                choices=[
                    ("D1BL", "1st. day, before lunch."),
                    ("D1BD", "1st. day, before dinner."),
                    ("D1AD", "1st. day, after dinner."),
                    ("D2BB", "2nd. day, before breakfast."),
                    ("D2BL", "2nd. day, before lunch."),
                    ("D2AL", "2nd. day, after lunch."),
                ],
                default="D2AL",
                max_length=4,
                verbose_name="departure time",
            ),
        ),
    ]
