# Generated by Django 4.2.8 on 2024-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_alter_personstay_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("21", "Project 21"),
                    ("PW", "Public Work"),
                    ("YW", "Youth Work"),
                    ("PG", "Guest of Pupil"),
                    ("A1", "1st. Aspect"),
                    ("A2", "2st. Aspect"),
                    ("A3", "3st. Aspect"),
                    ("A4", "4st. Aspect"),
                    ("GR", "Grail"),
                    ("A5", "5st. Aspect"),
                    ("A6", "6st. Aspect"),
                ],
                default="PW",
                max_length=20,
                verbose_name="aspect",
            ),
        ),
    ]
