# Generated by Django 4.2 on 2023-05-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0005_alter_person_sos_contact_alter_person_sos_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personstay",
            name="arrival_date",
            field=models.CharField(
                choices=[("D0", "Eve day"), ("D1", "1st day"), ("D2", "2nd day")],
                default="D1",
                max_length=2,
                verbose_name="arrival date",
            ),
        ),
    ]
