# Generated by Django 4.2.8 on 2024-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0006_alter_person_id_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="personstay",
            name="no_gluten",
            field=models.BooleanField(default=False, verbose_name="no gluten"),
        ),
        migrations.AddField(
            model_name="personstay",
            name="snorer",
            field=models.BooleanField(default=False, verbose_name="snorer"),
        ),
        migrations.AlterField(
            model_name="person",
            name="country",
            field=models.CharField(
                choices=[
                    ("BR", "Brazil"),
                    ("BO", "Bolivia"),
                    ("AR", "Argentina"),
                    ("US", "United States"),
                    ("NL", "Netherlands"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("ES", "Spain"),
                    ("PT", "Portugal"),
                    ("IT", "Italy"),
                    ("OC", "Other Country"),
                ],
                default="BR",
                max_length=2,
                verbose_name="country",
            ),
        ),
    ]
