# Generated by Django 4.2 on 2023-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0006_alter_personstay_arrival_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="personstay",
            name="bedroom_type",
            field=models.CharField(
                choices=[("B", "Bottom"), ("T", "Top")],
                default="B",
                max_length=1,
                verbose_name="bedroom type",
            ),
        ),
    ]
