# Generated by Django 4.2 on 2023-05-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0007_personstay_bedroom_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="personstay",
            name="departure_time",
            field=models.CharField(
                choices=[
                    ("BL1", "Before 1st lunch"),
                    ("AL1", "After 1st lunch"),
                    ("BDN", "Before dinner"),
                    ("ADN", "After dinner"),
                    ("BL2", "Before 2nd lunch"),
                    ("AL2", "After 2nd lunch"),
                    ("END", "End of event"),
                ],
                default="END",
                max_length=3,
                verbose_name="departure time",
            ),
        ),
    ]
