# Generated by Django 4.2 on 2023-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0008_personstay_departure_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="personstay",
            name="staff",
        ),
        migrations.AddField(
            model_name="personstay",
            name="staff",
            field=models.ManyToManyField(
                blank=True, to="person.staff", verbose_name="staff"
            ),
        ),
    ]
