# Generated by Django 4.2 on 2023-05-28 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0009_staff_remove_personstay_staff_personstay_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personstay",
            name="others",
        ),
    ]
