# Generated by Django 4.2 on 2023-05-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0010_remove_personstay_others"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personstay",
            name="arrival_date",
        ),
        migrations.AlterField(
            model_name="personstay",
            name="arrival_time",
            field=models.CharField(
                choices=[
                    ("0BD", "Eve day, before dinner."),
                    ("0AD", "Eve day, after dinner."),
                    ("1BB", "First day, before breakfast."),
                    ("1BL", "First day, before lunch."),
                    ("1BD", "First day, before dinner."),
                    ("1AD", "First day, after dinner."),
                    ("2BB", "Second day, before breakfast."),
                ],
                default="1BL",
                max_length=3,
                verbose_name="arrival time",
            ),
        ),
        migrations.AlterField(
            model_name="personstay",
            name="departure_time",
            field=models.CharField(
                choices=[
                    ("1BL", "First day, before lunch."),
                    ("1BD", "First day, before dinner."),
                    ("1AD", "First day, after dinner."),
                    ("2BB", "Second day, before breakfast."),
                    ("2BL", "Second day, before lunch."),
                    ("2AL", "Second day, after lunch."),
                ],
                default="2AL",
                max_length=3,
                verbose_name="departure time",
            ),
        ),
    ]
