# Generated by Django 4.2.1 on 2023-06-16 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0011_remove_personstay_arrival_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="short_name",
        ),
    ]
