# Generated by Django 4.2.7 on 2023-11-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("CNF", "Conference"),
                            ("SCF", "Special Conference"),
                            ("ODD", "Open Doors Day"),
                            ("OTR", "Others"),
                        ],
                        default="CNF",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("deadline", models.DateTimeField(verbose_name="deadline")),
                (
                    "ref_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="reference value"
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="minimum value"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPN", "open"), ("CLS", "closed")],
                        default="OPN",
                        max_length=3,
                        verbose_name="status",
                    ),
                ),
                (
                    "alt_mapping",
                    models.BooleanField(
                        default=False, verbose_name="alternate mapping"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="event.activity",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_event",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_event",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Mixed")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "bottom_or_top",
                    models.CharField(
                        choices=[("B", "Bottom"), ("T", "Top")],
                        default="B",
                        max_length=1,
                        verbose_name="bottom or topn",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bedroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodations",
                        to="center.bedroom",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "accommodation",
                "verbose_name_plural": "accommodations",
                "ordering": [
                    "-event__date",
                    "bedroom__building__name",
                    "bedroom__name",
                ],
            },
        ),
    ]
