# Generated by Django 4.2.8 on 2024-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="bottom_or_top",
            field=models.CharField(
                choices=[("B", "Bottom"), ("T", "Top")],
                default="B",
                max_length=1,
                verbose_name="bottom or top",
            ),
        ),
    ]
