# Generated by Django 4.2 on 2023-04-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "reg_deadline",
                    models.DateTimeField(verbose_name="registration deadline"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "ref_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="reference value"
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="minimum value"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPN", "open"), ("CLS", "closed")],
                        default="OPN",
                        max_length=3,
                        verbose_name="status",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="event.activity",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["-start_date"],
            },
        ),
    ]
