# Generated by Django 4.2.8 on 2024-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_alter_accommodation_bottom_or_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("CNF", "Conference"),
                    ("ODD", "Open Doors Day"),
                    ("OTR", "Others"),
                ],
                default="CNF",
                max_length=3,
                verbose_name="type",
            ),
        ),
    ]
