# Generated by Django 4.2.8 on 2024-02-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_activity_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("OPN", "open"), ("CLS", "closed"), ("SRT", "shortly")],
                default="OPN",
                max_length=3,
                verbose_name="status",
            ),
        ),
    ]
