# Generated by Django 4.2 on 2023-04-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_event_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedroomMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapping", models.JSONField(verbose_name="mapping")),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="event.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "bedroom mapping",
                "verbose_name_plural": "bedrooms mapping",
                "ordering": ["-event__date"],
            },
        ),
    ]
