# Generated by Django 4.2 on 2023-05-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0006_alter_bedroom_gender"),
        ("person", "0006_alter_personstay_arrival_date"),
        ("event", "0005_bedroommapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Mixed")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "up_down",
                    models.CharField(
                        choices=[("U", "Up"), ("D", "Down")],
                        default="U",
                        max_length=1,
                        verbose_name="up or down",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bedroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodations",
                        to="center.bedroom",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="event.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accommodations",
                        to="person.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "accommodation",
                "verbose_name_plural": "accommodations",
                "ordering": [
                    "-event__date",
                    "bedroom__building__name",
                    "bedroom__name",
                ],
            },
        ),
        migrations.DeleteModel(
            name="BedroomMapping",
        ),
    ]
