# Generated by Django 4.2 on 2023-05-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0006_alter_personstay_arrival_date"),
        ("event", "0006_accommodation_delete_bedroommapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accommodations",
                to="person.person",
            ),
        ),
    ]
