# Generated by Django 4.2 on 2023-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_alter_accommodation_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="up_down",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="bottom_or_top",
            field=models.CharField(
                choices=[("B", "Bottom"), ("T", "Top")],
                default="B",
                max_length=1,
                verbose_name="bottom or topn",
            ),
        ),
    ]
