# Generated by Django 4.2 on 2023-05-18 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_remove_accommodation_up_down_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="person",
        ),
    ]
