# Generated by Django 4.2 on 2023-05-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_remove_accommodation_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="alt_mapping",
            field=models.BooleanField(default=False),
        ),
    ]
