# Generated by Django 4.2 on 2023-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_event_alt_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="alt_mapping",
            field=models.BooleanField(default=False, verbose_name="alternate mapping"),
        ),
    ]
