# Generated by Django 4.2.7 on 2023-11-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="short name"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="state"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("BR", "Brazil"), ("US", "United States")],
                        default="BR",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "contact",
                    models.ManyToManyField(
                        related_name="centers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "center",
                "verbose_name_plural": "centers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "building",
                "verbose_name_plural": "buildings",
                "ordering": ["center", "name"],
            },
        ),
        migrations.CreateModel(
            name="Bedroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Mixed")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                ("floor", models.IntegerField(default=0, verbose_name="floor")),
                ("bottom_beds", models.IntegerField(verbose_name="bottom beds")),
                ("top_beds", models.IntegerField(verbose_name="top beds")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "building",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "bedroom",
                "verbose_name_plural": "bedrooms",
                "ordering": ["building", "name"],
            },
        ),
    ]
