# Generated by Django 4.2.16 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='abbr',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='abbr'),
        ),
        migrations.AlterField(
            model_name='center',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('BO', 'Bolivia'), ('AR', 'Argentina'), ('US', 'United States'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('PT', 'Portugal'), ('IT', 'Italy'), ('OC', 'Other Country')], default='BR', max_length=2, verbose_name='country'),
        ),
    ]
