# Generated by Django 4.2 on 2023-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0002_alter_center_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="short_name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="short name"
            ),
        ),
    ]
