# Generated by Django 4.2 on 2023-04-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0003_alter_center_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "building",
                "verbose_name_plural": "buildings",
                "ordering": ["center", "name"],
            },
        ),
        migrations.CreateModel(
            name="Bedroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                ("floor", models.IntegerField(default=0, verbose_name="floor")),
                ("beds", models.IntegerField(verbose_name="beds")),
                ("bunks", models.IntegerField(verbose_name="bunks")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "building",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "bedroom",
                "verbose_name_plural": "bedrooms",
                "ordering": ["building", "name"],
            },
        ),
    ]
