# Generated by Django 4.2 on 2023-05-04 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0004_building_bedroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="contact",
        ),
        migrations.AddField(
            model_name="center",
            name="contact",
            field=models.ManyToManyField(
                related_name="centers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contact",
            ),
        ),
    ]
