# Generated by Django 4.2 on 2023-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0005_remove_center_contact_center_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedroom",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("X", "Mixed")],
                default="M",
                max_length=1,
                verbose_name="gender",
            ),
        ),
    ]
