# Generated by Django 4.2 on 2023-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0006_alter_bedroom_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bedroom",
            name="beds",
        ),
        migrations.RemoveField(
            model_name="bedroom",
            name="bunks",
        ),
        migrations.AddField(
            model_name="bedroom",
            name="bottom_beds",
            field=models.IntegerField(default=4, verbose_name="bottom beds"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bedroom",
            name="top_beds",
            field=models.IntegerField(default=4, verbose_name="top beds"),
            preserve_default=False,
        ),
    ]
