# Generated by Django 4.2 on 2023-05-16 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0007_remove_bedroom_beds_remove_bedroom_bunks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="description",
        ),
    ]
