# Generated by Django 4.2 on 2023-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "bank flag",
                "verbose_name_plural": "bank flags",
                "ordering": ["name"],
            },
        ),
    ]
