# Generated by Django 4.2.7 on 2023-11-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "bank flag",
                "verbose_name_plural": "bank flags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="value"
                    ),
                ),
                (
                    "credit_launch",
                    models.BooleanField(default=False, verbose_name="credit launch"),
                ),
                (
                    "late_payment",
                    models.BooleanField(default=False, verbose_name="late payment"),
                ),
                (
                    "canceled_payment",
                    models.BooleanField(default=False, verbose_name="canceled payment"),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="center.center",
                        verbose_name="center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="event.event",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lodge",
                    models.CharField(
                        choices=[("LDG", "Lodge"), ("HSE", "House"), ("HTL", "Hotel")],
                        default="LDG",
                        max_length=3,
                        verbose_name="lodge",
                    ),
                ),
                (
                    "no_stairs",
                    models.BooleanField(default=False, verbose_name="no stairs"),
                ),
                ("no_bunk", models.BooleanField(default=False, verbose_name="no bunk")),
                (
                    "arrival_time",
                    models.CharField(
                        choices=[
                            ("0BD", "Eve day, before dinner."),
                            ("0AD", "Eve day, after dinner."),
                            ("1BB", "First day, before breakfast."),
                            ("1BL", "First day, before lunch."),
                            ("1BD", "First day, before dinner."),
                            ("1AD", "First day, after dinner."),
                            ("2BB", "Second day, before breakfast."),
                        ],
                        default="1BL",
                        max_length=3,
                        verbose_name="arrival time",
                    ),
                ),
                (
                    "departure_time",
                    models.CharField(
                        choices=[
                            ("1BL", "First day, before lunch."),
                            ("1BD", "First day, before dinner."),
                            ("1AD", "First day, after dinner."),
                            ("2BB", "Second day, before breakfast."),
                            ("2BL", "Second day, before lunch."),
                            ("2AL", "Second day, after lunch."),
                        ],
                        default="2AL",
                        max_length=3,
                        verbose_name="departure time",
                    ),
                ),
                ("housed", models.BooleanField(default=False, verbose_name="housed")),
                (
                    "staff",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="staff"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="value"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "accommodation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register",
                        to="event.accommodation",
                        verbose_name="accommodation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registers",
                        to="register.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers",
                        to="person.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "register",
                "verbose_name_plural": "registers",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="FormOfPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CSH", "Cash"),
                            ("CHK", "Check"),
                            ("PRE", "Pre Check"),
                            ("DBT", "Debit"),
                            ("CDT", "Credit"),
                            ("DPT", "Deposit"),
                            ("TRF", "Transfer"),
                            ("PIX", "Pix"),
                            ("FRE", "Free"),
                        ],
                        default="CSH",
                        max_length=3,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "ctrl",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="control number",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="value"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "bank_flag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments",
                        to="register.bankflag",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_of_payments",
                        to="register.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments",
                        to="person.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "form of payment",
                "verbose_name_plural": "form of payments",
                "ordering": ["-created_on"],
            },
        ),
    ]
