# Generated by Django 4.2 on 2023-04-28 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0004_building_bedroom"),
        ("person", "0003_alter_creditlog_operation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0004_alter_event_end_date"),
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormOfPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CSH", "Cash"),
                            ("CHK", "Check"),
                            ("PRE", "Pre Check"),
                            ("DBT", "Debit"),
                            ("CDT", "Credit"),
                            ("DPT", "Deposit"),
                            ("TRF", "Transfer"),
                            ("GSC", "Guest Credit"),
                            ("FRE", "Free"),
                        ],
                        default="CSH",
                        max_length=3,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "ctrl",
                    models.CharField(max_length=50, verbose_name="control number"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="value"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "bank_flag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments",
                        to="register.bankflag",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments",
                        to="person.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_of_payments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "form of payment",
                "verbose_name_plural": "form of payments",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lodge",
                    models.CharField(
                        choices=[("LDG", "Lodge"), ("HSE", "House"), ("HTL", "Hotel")],
                        default="LDG",
                        max_length=3,
                        verbose_name="lodge",
                    ),
                ),
                (
                    "no_stairs",
                    models.BooleanField(default=False, verbose_name="no stairs"),
                ),
                ("no_bunk", models.BooleanField(default=False, verbose_name="no bunk")),
                (
                    "arrival_date",
                    models.CharField(
                        choices=[
                            ("D0", "Eve day"),
                            ("D1", "First day"),
                            ("D2", "Secound day"),
                        ],
                        default="D1",
                        max_length=2,
                        verbose_name="arrival date",
                    ),
                ),
                (
                    "arrival_time",
                    models.CharField(
                        choices=[
                            ("BB", "Before breakfast"),
                            ("BL", "Before lunch"),
                            ("BD", "Before diner"),
                            ("AD", "After diner"),
                        ],
                        default="BL",
                        max_length=2,
                        verbose_name="arrival time",
                    ),
                ),
                ("housed", models.BooleanField(default=False, verbose_name="housed")),
                (
                    "staff",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KIT", "Kitchen"),
                            ("DSW", "Dishwashing"),
                            ("REF", "Refectory"),
                            ("ACC", "Accommodation"),
                            ("EXT", "External Area"),
                            ("AFT", "Aftermath"),
                            ("SNK", "Snack"),
                            ("BRF", "Breakfast"),
                            ("TPL", "Temple"),
                            ("LDR", "Laundry"),
                            ("MTP", "Multiple"),
                            ("CNT", "Center Team"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="staff",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="value"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "bedroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.bedroom",
                        verbose_name="bedroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers",
                        to="person.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "register",
                "verbose_name_plural": "registers",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="value"
                    ),
                ),
                (
                    "credit_launch",
                    models.BooleanField(default=False, verbose_name="credit launch"),
                ),
                (
                    "late_payment",
                    models.BooleanField(default=False, verbose_name="late payment"),
                ),
                (
                    "canceled_payment",
                    models.BooleanField(default=False, verbose_name="canceled payment"),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="event.event",
                    ),
                ),
                (
                    "form_of_payments",
                    models.ManyToManyField(
                        to="register.formofpayment", verbose_name="form of payments"
                    ),
                ),
                (
                    "registers",
                    models.ManyToManyField(
                        to="register.register", verbose_name="registers"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_on"],
            },
        ),
    ]
