# Generated by Django 4.2 on 2023-04-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_formofpayment_register_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formofpayment",
            name="bank_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_of_payments",
                to="register.bankflag",
            ),
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="ctrl",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="control number"
            ),
        ),
    ]
