# Generated by Django 4.2.8 on 2024-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0003_alter_register_arrival_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="credit_launch",
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CSH", "Cash"),
                    ("CHK", "Check"),
                    ("PRE", "Pre Check"),
                    ("DBT", "Debit"),
                    ("DPT", "Deposit"),
                    ("TRF", "Transfer"),
                    ("PIX", "Pix"),
                    ("FRE", "Free"),
                ],
                default="CSH",
                max_length=3,
                verbose_name="payment type",
            ),
        ),
    ]
