# Generated by Django 4.2 on 2023-04-29 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("center", "0004_building_bedroom"),
        ("register", "0003_alter_formofpayment_bank_flag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="center",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="center.center",
                verbose_name="center",
            ),
        ),
    ]
