# Generated by Django 4.2.8 on 2024-02-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0004_remove_order_credit_launch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formofpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CSH", "Cash"),
                    ("CHK", "Check"),
                    ("PRE", "Pre Check"),
                    ("DBT", "Debit"),
                    ("CDT", "Credit"),
                    ("DPT", "Deposit"),
                    ("TRF", "Transfer"),
                    ("PIX", "Pix"),
                    ("FRE", "Free"),
                    ("PND", "Pending"),
                    ("PCD", "Person Credit"),
                ],
                default="CSH",
                max_length=3,
                verbose_name="payment type",
            ),
        ),
    ]
