# Generated by Django 4.2.8 on 2024-02-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0005_alter_formofpayment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="no_gluten",
            field=models.BooleanField(default=False, verbose_name="no gluten"),
        ),
        migrations.AddField(
            model_name="register",
            name="snorer",
            field=models.BooleanField(default=False, verbose_name="snorer"),
        ),
    ]
