# Generated by Django 4.2 on 2023-05-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0009_register_departure_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="description",
        ),
        migrations.AlterField(
            model_name="register",
            name="staff",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="staff"
            ),
        ),
    ]
