# Generated by Django 4.2 on 2023-07-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0011_remove_register_arrival_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formofpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CSH", "Cash"),
                    ("CHK", "Check"),
                    ("PRE", "Pre Check"),
                    ("DBT", "Debit"),
                    ("CDT", "Credit"),
                    ("DPT", "Deposit"),
                    ("TRF", "Transfer"),
                    ("PIX", "Pix"),
                    ("FRE", "Free"),
                ],
                default="CSH",
                max_length=3,
                verbose_name="payment type",
            ),
        ),
    ]
