# Generated by Django 4.2 on 2023-04-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("CNF", "Conference"),
                            ("SCF", "Special Conference"),
                            ("ODD", "Open Doors Day"),
                            ("OTR", "Others"),
                        ],
                        default="CNF",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "bank flag",
                "verbose_name_plural": "bank flags",
                "ordering": ["name"],
            },
        ),
    ]
